//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAmigoSecretoOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amigo_Oculto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Amigo_Oculto()
        {
            this.Sorteio = new HashSet<Sorteio>();
            this.Topico = new HashSet<Topico>();
            this.Usuario_Amigo_Oculto = new HashSet<Usuario_Amigo_Oculto>();
        }
    
        public int Id_amigo_oculto { get; set; }
        public string Nome_amigo_oculto { get; set; }
        public string Descricao { get; set; }
        public System.DateTime Data_revelacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sorteio> Sorteio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topico> Topico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Amigo_Oculto> Usuario_Amigo_Oculto { get; set; }
    }
}
