//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAmigoSecretoOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amigos
    {
        public int Id_amigo { get; set; }
        public System.DateTime Data_solicitacao { get; set; }
        public System.DateTime Data_confirmacao { get; set; }
        public string Situacao { get; set; }
        public int Fk_usuario_solicitante { get; set; }
        public int Fk_usuario_destino { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
