//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAmigoSecretoOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityDataModel : DbContext
    {
        public EntityDataModel()
            : base("name=EntityDataModel")
        {
        }
        
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amigo_Oculto> Amigo_Oculto { get; set; }
        public virtual DbSet<Amigos> Amigos { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Sorteio> Sorteio { get; set; }
        public virtual DbSet<Topico> Topico { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Usuario_Amigo_Oculto> Usuario_Amigo_Oculto { get; set; }
    }
}
