//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAmigoSecretoOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorteio
    {
        public int Id_sorteio { get; set; }
        public int Fk_usuario_inicio { get; set; }
        public int Fk_amigo_oculto { get; set; }
        public int Fk_usuario_fim { get; set; }
    
        public virtual Amigo_Oculto Amigo_Oculto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
