//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAmigoSecretoOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topico()
        {
            this.Post = new HashSet<Post>();
        }
    
        public int Id_Topico { get; set; }
        public string Discursao { get; set; }
        public System.DateTime Data_inicio { get; set; }
        public int Fk_amigo_oculto { get; set; }
    
        public virtual Amigo_Oculto Amigo_Oculto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Post { get; set; }
    }
}
